package main;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.SQLException;

/**
 * Handles keyboard input for the game, managing player movement, game state transitions,
 * and interactions with the database for game session management.
 */
public class KeyHandler implements KeyListener {

	Panel gp; // Reference to the game panel
	public boolean upPressed, downPressed, leftPressed, rightPressed, enterPressed;


	/**
	 * Constructor for KeyHandler.
	 *
	 * @param gp The main game panel instance, providing access to game state and other game components.
	 */
	public KeyHandler(Panel gp) {
		this.gp = gp;

	}

	/**
	 * Invoked when a key has been typed.
	 * This event occurs when a character is generated by a keyboard input.
	 * (Not used for direct game input in this implementation).
	 *
	 * @param e The KeyEvent generated by the system.
	 */
	@Override
	public void keyTyped(KeyEvent e) {


	}

	/**
	 * Invoked when a key has been pressed.
	 * This method handles various key presses to control player movement,
	 * change game states, and manage game sessions with the database.
	 *
	 * @param e The KeyEvent generated by the system.
	 */
	@Override
	public void keyPressed(KeyEvent e) {

		int code = e.getKeyCode();

		// PLAY STATE actions
		if (gp.gameState == gp.playState){

		if(code == KeyEvent.VK_W) {
			upPressed = true; // W key is pressed (up)
		}
		if (code == KeyEvent.VK_S) {
			downPressed = true; // S key is pressed (down)
		}
		if (code == KeyEvent.VK_A) {
			leftPressed = true; // A key is pressed (left)
		}
		if (code == KeyEvent.VK_D) {
			rightPressed = true; // D key is pressed (right)
		}
		if (code == KeyEvent.VK_P) {
			gp.gameState = gp.pauseState; // Change to pause state

			// Reset movement input to prevent unintended input on unpause
			upPressed = false;
        	downPressed = false;
        	leftPressed = false;
       		rightPressed = false;
		}
		if (code == KeyEvent.VK_ENTER){
			enterPressed = true;
		}
	}
		// PAUSE STATE actions
		else if (gp.gameState==gp.pauseState){
			if (code == KeyEvent.VK_P) {
			gp.gameState = gp.playState; // Change to play state
		}
	}
		// DIALOGUE STATE actions
		else if (gp.gameState == gp.dialogueState){
		if (code == KeyEvent.VK_ENTER){
			enterPressed = true;
		}
	}

		// QUIZ STATE actions
		else if (gp.gameState == gp.quizState){
    	if (code == KeyEvent.VK_W) { // Move selection Up
        	gp.quizSelection--;
        if (gp.quizSelection < 0) {
            	gp.quizSelection = gp.options[gp.currentQuestion].length - 1; // Wrap around
        	}
    	}
    	if (code == KeyEvent.VK_S) { // Move selection Down
       		gp.quizSelection++;
        if (gp.quizSelection >= gp.options[gp.currentQuestion].length) {
           		 gp.quizSelection = 0; // Wrap around
        	}
    	}
   		if (code == KeyEvent.VK_ENTER){
        	enterPressed = true; // Set flag to be handled in Panel update/logic
   		 }
	}
		// GAME FINISHED state actions
		if (gp.ui.gameFinishedPass || gp.ui.gameFinishedFail) {
    	if (code == KeyEvent.VK_ENTER) {
        // Reset game variables
        	gp.resetGame();

        // Change the game state back to the Title Screen
        	gp.gameState = gp.titleState;
			 enterPressed = false;
			return;
    }
}

		// TITLE STATE actions
		if (gp.gameState == gp.titleState){
    	if (code == KeyEvent.VK_W) { // Move selection Up
        	gp.ui.commandNum--;
        if (gp.ui.commandNum < 0) {
            gp.ui.commandNum = 1; // Wrap around
        }
    }
    	if (code == KeyEvent.VK_S) { // Move selection Down
       		 gp.ui.commandNum++;
        if (gp.ui.commandNum > 1) {
            gp.ui.commandNum = 0; // Wrap around
        }
    }
    if (code == KeyEvent.VK_ENTER){
		if (gp.ui.commandNum == 0){ // Option: NEW GAME
			// Close previous overall game session (game_sessions table) if active
            if (gp.gameId != -1) {
                try {
                    DatabaseManager.updateEndTime(gp.gameId);
                    System.out.println("Previous overall game session " + gp.gameId + " ended.");
                } catch (SQLException ex) {
                    System.err.println("Error updating end time for previous overall game session: " + ex.getMessage());
                    ex.printStackTrace();
                }
            }

            // Close previous game-specific session ('games' table) if active
            if (gp.ui.gameId != -1) {
                GameDataClient.closeGameSession(gp.ui.gameId);
                System.out.println("Previous game-specific session " + gp.ui.gameId + " ended.");
            }

            // Create a new overall game session (game_sessions table)
            try {
                gp.gameId = DatabaseManager.createGameSession();
                System.out.println("New overall game session started with ID: " + gp.gameId);
            } catch (SQLException ex) {
                System.err.println("Error creating overall game session: " + ex.getMessage());
                ex.printStackTrace();
            }

            // Create a corresponding entry in the 'games' table via GameDataClient
            String sessionName = "Game Session (Overall ID: " + gp.gameId + ") - " + System.currentTimeMillis();
            int newGameSpecificId = GameDataClient.createGameSession(sessionName, "Player started a new game");
            gp.ui.setGameId(newGameSpecificId); // This gameId is for the 'games' table
            System.out.println("New game-specific session started with ID: " + gp.ui.gameId);

			gp.gameState = gp.playState; // Transition to play state
			if (gp.gameThread == null) {
                gp.startGameThread(); // Start the game thread if it's not already running
            }
		}
		if (gp.ui.commandNum == 1){ // Option: EXIT
			// Close current overall game session (game_sessions table) if active
            if (gp.gameId != -1) {
                try {
                    DatabaseManager.updateEndTime(gp.gameId);
                    System.out.println("Overall game session " + gp.gameId + " ended.");
                } catch (SQLException ex) {
                    System.err.println("Error updating end time for overall game session: " + ex.getMessage());
                    ex.printStackTrace();
                }
            }

            // Close current game-specific session ('games' table) if active
            if (gp.ui.gameId != -1) {
                GameDataClient.closeGameSession(gp.ui.gameId);
                System.out.println("Game-specific session " + gp.ui.gameId + " ended.");
            }
			System.exit(0); // Exit the application
		}

    }
}
}

	/**
	 * Invoked when a key has been released.
	 * This method tracks the release of movement keys to stop player actions.
	 *
	 * @param e The KeyEvent generated by the system.
	 */
	@Override
	public void keyReleased(KeyEvent e) {

		int code =  e.getKeyCode();

		if(code == KeyEvent.VK_W) {
			upPressed = false; // W key is released
		}
		if (code == KeyEvent.VK_S) {
			downPressed = false; // S key is released
		}
		if (code == KeyEvent.VK_A) {
			leftPressed = false; // A key is released
		}
		if (code == KeyEvent.VK_D) {
			rightPressed = false; // D key is released
		}
		if (code == KeyEvent.VK_ENTER){
			enterPressed = false;
		}

	}


}