package main;

import javax.swing.JFrame;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;

/**
 * A custom WindowAdapter that handles the window closing event.
 * It is responsible for updating the end times of both the overall game session
 * and the specific game session in the database when the application window is closed.
 */
public class MyWindowCloser extends WindowAdapter {
    private final Panel gp; // Reference to the game panel
    private final JFrame window; // Reference to the application window

    /**
     * Constructs a MyWindowCloser with references to the game panel and the application window.
     *
     * @param gp     The main game panel instance, containing game-related data like gameId.
     * @param window The JFrame window that this adapter will listen to for closing events.
     */
    public MyWindowCloser(Panel gp, JFrame window) {
        this.gp = gp;
        this.window = window;
    }

    /**
     * Overrides the windowClosing method to perform cleanup operations when the window is closed.
     * This includes updating database records for game sessions and exiting the application.
     *
     * @param windowEvent The window event generated by the system.
     */
    @Override
    public void windowClosing(WindowEvent windowEvent) {
        // Close current overall game session (game_sessions table) if active.
        // This is managed by DatabaseManager for the high-level application session.
        if (gp.gameId != -1) {
            try {
                DatabaseManager.updateEndTime(gp.gameId);
                System.out.println("Overall game session " + gp.gameId + " ended from window close.");
            } catch (SQLException ex) {
                System.err.println("Error updating end time for overall game session on window close: " + ex.getMessage());
                ex.printStackTrace();
            }
        }

        // Close current game-specific session ('games' table) if active.
        // This is managed by GameDataClient for individual game instances within the application.
        if (gp.ui.gameId != -1) {
            GameDataClient.closeGameSession(gp.ui.gameId);
            System.out.println("Game-specific session " + gp.ui.gameId + " ended from window close.");
        }
        
        // Dispose of the window and exit the application.
        window.dispose();
        System.exit(0);
    }
}